# -*- coding: utf-8 -*-

from typing import Dict, List, Any, Optional, Tuple
import math
import numpy as np

from .geometry import make_lateral_offset_route, make_stop_route
from .bicycle_model import rollout, closest_s, pure_pursuit_steer, longitudinal_accel, bicycle_step
from .dataset import get_current_ego_state


def _cfg_get(obj: Any, key: str, default=None):
    if obj is None:
        return default
    try:
        return getattr(obj, key)
    except Exception:
        pass
    if isinstance(obj, dict):
        return obj.get(key, default)
    return default


def _cfg_float(obj: Any, key: str, default: float) -> float:
    try:
        return float(_cfg_get(obj, key, default))
    except Exception:
        return float(default)


def _cfg_list(obj: Any, key: str, default) -> List[float]:
    value = _cfg_get(obj, key, default)
    try:
        return [float(v) for v in value]
    except Exception:
        return [float(v) for v in default]


def _future_speed_profile_from_waypoints(expert_future: Optional[np.ndarray], cfg) -> Optional[np.ndarray]:

    if expert_future is None:
        return None
    pts = np.asarray(expert_future, dtype=np.float32)
    if pts.ndim != 2 or len(pts) == 0 or pts.shape[1] < 2:
        return None

    n = int(cfg.horizon.num_future_waypoints)
    pts = pts[:, :2]
    origin = np.zeros((1, 2), dtype=np.float32)
    steps = np.linalg.norm(np.diff(np.vstack([origin, pts]), axis=0), axis=1)
    speeds = steps * float(cfg.horizon.future_fps)
    speeds = np.where(np.isfinite(speeds), speeds, 0.0).astype(np.float32)
    speeds = np.clip(speeds, 0.0, float(cfg.bicycle.max_speed_mps))

    if len(speeds) >= n:
        return speeds[:n].astype(np.float32)
    if len(speeds) == 0:
        return None
    return np.pad(speeds, (0, n - len(speeds)), mode="edge").astype(np.float32)


def _estimate_expert_reference_speed(expert_future: Optional[np.ndarray], cfg) -> float:
    profile = _future_speed_profile_from_waypoints(expert_future, cfg)
    if profile is None:
        return 0.0
    finite = profile[np.isfinite(profile)]
    finite = finite[finite > 0.2]
    if len(finite) == 0:
        return 0.0
    ref = float(np.percentile(finite, 75))
    if ref < 1.0:
        return 0.0
    return float(np.clip(ref, 0.0, float(cfg.bicycle.max_speed_mps)))


def current_target_speed(measurement: Dict, cfg, expert_future: Optional[np.ndarray] = None) -> float:
    
    # 1. 当前帧车速
    cur = max(float(measurement.get("speed", 0.0)), 0.0) 
    
    # 2. 目标车速
    key = str(cfg.behaviors.target_speed_key)  # target_speed
    try:
        target = float(measurement.get(key, cur))  
    except Exception:
        target = cur
    
    if target <= 0.1:
        target = cur

    # 专家未来轨迹故基础的参考速度
    expert_ref = _estimate_expert_reference_speed(expert_future, cfg)
    if expert_ref > max(target, cur, 0.0):
        target = expert_ref

    return float(np.clip(target, 0.0, float(cfg.bicycle.max_speed_mps)))


def nominal_speed_profile(measurement: Dict, cfg, expert_future: Optional[np.ndarray] = None) -> np.ndarray:

    n = int(cfg.horizon.num_future_waypoints)  # waypoints的数量
    nominal = current_target_speed(measurement, cfg, expert_future=expert_future)
    return np.full((n,), nominal, dtype=np.float32)


def _active_rule_hold_required(
    factor: Dict,
    measurement: Dict,
    expert_future: Optional[np.ndarray],
    cfg,
) -> bool:
    """Return True only for an already-stopped active red-light rule.

    A red light remains an active barrier until the signal changes, so an ego
    vehicle that is already stopped should hold its current pose.  A stop sign
    is different: after a complete stop and a short hold, the vehicle is allowed
    to proceed.  Stop-sign responses are therefore generated by the dedicated
    stop-then-go state machine below and must never be converted into an
    all-horizon stationary hold here.
    """
    ftype = str((factor or {}).get("type", ""))
    if ftype != "red_light_stop_line":
        return False

    current_active = bool(((factor or {}).get("red_light_rule") or {}).get("current_red_active", False))
    if not current_active:
        return False

    rule_cfg = _cfg_get(cfg, "traffic_rules", {})
    current_speed_threshold = _cfg_float(rule_cfg, "hold_stop_speed_threshold_mps", 0.20)
    expert_displacement_threshold = _cfg_float(rule_cfg, "hold_stop_expert_displacement_m", 0.20)

    pts = None
    if expert_future is not None:
        try:
            arr = np.asarray(expert_future, dtype=np.float32)
            if arr.ndim == 2 and len(arr) > 0 and arr.shape[1] >= 2:
                pts = arr[:, :2]
        except Exception:
            pts = None

    if pts is not None and np.isfinite(pts).all():
        max_displacement = float(np.max(np.linalg.norm(pts, axis=1)))
        if max_displacement <= expert_displacement_threshold:
            return True

    current_speed = max(float(measurement.get("speed", 0.0)), 0.0)
    return current_speed <= current_speed_threshold


def _stationary_hold_rollout(cfg) -> Dict:
    """Build an explicit stationary rollout for an already-stopped rule state."""
    n_wp = int(cfg.horizon.num_future_waypoints)
    ratio = float(cfg.horizon.model_fps) / float(cfg.horizon.future_fps)
    save_stride = int(round(ratio))
    if abs(ratio - save_stride) > 1e-6:
        raise ValueError(
            f"model_fps/future_fps must be integer. Got {cfg.horizon.model_fps}/{cfg.horizon.future_fps}"
        )
    dense_steps = n_wp * save_stride

    waypoints = np.zeros((n_wp, 2), dtype=np.float32)
    yaws = np.zeros((n_wp,), dtype=np.float32)
    speeds = np.zeros((n_wp,), dtype=np.float32)
    controls = np.zeros((n_wp, 2), dtype=np.float32)
    dense_xy = np.zeros((dense_steps, 2), dtype=np.float32)
    dense_yaw = np.zeros((dense_steps,), dtype=np.float32)
    dense_speed = np.zeros((dense_steps,), dtype=np.float32)
    dense_controls = np.zeros((dense_steps, 2), dtype=np.float32)
    target_profile = np.zeros((n_wp,), dtype=np.float32)
    dense_target = np.zeros((dense_steps,), dtype=np.float32)

    return {
        "waypoints": waypoints,
        "yaws": yaws,
        "speeds": speeds,
        "controls": controls,
        "dense_xy": dense_xy,
        "dense_yaw": dense_yaw,
        "dense_speed": dense_speed,
        "dense_controls": dense_controls,
        "target_speed": 0.0,
        "target_speed_profile": target_profile,
        "dense_target_speed_profile": dense_target,
    }


def _stop_sign_stop_then_go_rollout(
    base_route: np.ndarray,
    factor: Dict,
    measurement: Dict,
    cfg,
    expert_future: Optional[np.ndarray] = None,
) -> Dict:
    """Roll out a stateful complete-stop response for an active stop sign.

    The candidate follows four explicit phases:

    1. approach the required stop position without unnecessary acceleration;
    2. brake to a complete stop before the controlled region;
    3. remain below the complete-stop speed for the configured duration;
    4. release and continue along the original route.

    The original stop-sign implementation reused the generic ``yield_stop``
    candidate, which truncates the route and sets the target speed to zero for
    the whole horizon.  That behavior is appropriate for a persistent barrier
    such as a red light, but not for a stop sign that may be crossed after the
    stop has been completed.
    """
    route = np.asarray(base_route, dtype=np.float32)
    if route.ndim != 2 or len(route) < 2 or route.shape[1] < 2:
        route = np.asarray([[0.0, 0.0], [1.0, 0.0]], dtype=np.float32)
    else:
        route = route[:, :2].astype(np.float32)

    ratio = float(cfg.horizon.model_fps) / float(cfg.horizon.future_fps)
    save_stride = int(round(ratio))
    if abs(ratio - save_stride) > 1e-6:
        raise ValueError(
            f"model_fps/future_fps must be integer. Got {cfg.horizon.model_fps}/{cfg.horizon.future_fps}"
        )

    n_wp = int(cfg.horizon.num_future_waypoints)
    dense_steps = n_wp * save_stride
    dt = 1.0 / float(cfg.horizon.model_fps)

    rule_cfg = _cfg_get(cfg, "traffic_rules", {})
    stop_speed = max(_cfg_float(rule_cfg, "stop_sign_complete_speed_mps", 0.20), 0.0)
    stop_duration_s = max(_cfg_float(rule_cfg, "stop_sign_complete_duration_s", 0.50), 0.0)
    hold_steps_required = max(int(math.ceil(stop_duration_s * float(cfg.horizon.model_fps))), 1)
    completion_max_distance = max(
        _cfg_float(rule_cfg, "stop_sign_completion_max_distance_m", 2.0),
        0.0,
    )
    approach_decel = max(_cfg_float(rule_cfg, "stop_sign_approach_decel_mps2", 4.0), 0.1)
    brake_buffer = max(_cfg_float(rule_cfg, "stop_sign_brake_buffer_m", 0.75), 0.0)
    approach_speed_cap = max(_cfg_float(rule_cfg, "stop_sign_approach_speed_mps", 4.0), stop_speed)
    capture_margin = max(_cfg_float(rule_cfg, "stop_sign_target_position_tolerance_m", 0.15), 0.0)
    release_fallback_speed = max(_cfg_float(rule_cfg, "stop_sign_release_speed_mps", 4.0), 0.0)

    stop_distance = max(_stop_distance_for_actor(factor, cfg, emergency=False), 0.0)
    nominal_release_speed = current_target_speed(measurement, cfg, expert_future=expert_future)
    if nominal_release_speed <= stop_speed:
        nominal_release_speed = release_fallback_speed
    nominal_release_speed = float(np.clip(nominal_release_speed, 0.0, float(cfg.bicycle.max_speed_mps)))

    state = get_current_ego_state(measurement)
    dense_states = []
    dense_controls = []
    dense_targets = []
    saved_states = []
    saved_controls = []
    prev_steer = 0.0

    current_speed = max(float(measurement.get("speed", 0.0)), 0.0)
    approach_cruise_speed = min(
        nominal_release_speed,
        max(current_speed, min(nominal_release_speed, approach_speed_cap)),
    )

    phase = "approach"
    hold_count = 0
    release_started = False
    stop_completed = False
    completion_dense_step = None
    release_dense_step = None

    def stop_condition(cur_state: Dict) -> bool:
        progress = closest_s(route, cur_state)
        remaining = max(stop_distance - progress, 0.0)
        return float(cur_state["v"]) <= stop_speed and remaining <= completion_max_distance

    for step in range(dense_steps):
        # An already-stopped ego near the controlled region begins in the hold
        # phase immediately.  This is intentionally different from a red-light
        # hold: the state machine will release after the required stop duration.
        if phase == "approach" and stop_condition(state):
            phase = "hold"
            hold_count = 0

        progress = closest_s(route, state)
        remaining = max(stop_distance - progress, 0.0)

        if phase == "approach":
            # Estimate the remaining physical braking distance from the current
            # speed.  Once the trigger is reached, enter an explicit braking
            # phase instead of relying on a slowly converging proportional speed
            # controller to reach zero.
            braking_distance = (float(state["v"]) ** 2) / max(2.0 * approach_decel, 1e-6)
            if remaining <= braking_distance + brake_buffer or remaining <= capture_margin:
                phase = "brake"
                target_speed = 0.0
            else:
                target_speed = approach_cruise_speed
        elif phase == "brake":
            target_speed = 0.0
        elif phase == "hold":
            target_speed = 0.0
        else:
            target_speed = nominal_release_speed

        raw_steer = pure_pursuit_steer(route, state, cfg)
        max_delta = float(cfg.bicycle.max_steer_rate_radps) * dt
        steer = float(np.clip(raw_steer, prev_steer - max_delta, prev_steer + max_delta))
        prev_steer = steer
        if phase == "brake" and float(state["v"]) > stop_speed:
            acc = max(float(cfg.bicycle.min_accel_mps2), -approach_decel)
        else:
            acc = longitudinal_accel(float(state["v"]), float(target_speed), cfg)
        state = bicycle_step(state, steer, acc, dt, cfg)

        dense_states.append([state["x"], state["y"], state["yaw"], state["v"]])
        dense_controls.append([steer, acc])
        dense_targets.append(float(target_speed))

        if phase in ["approach", "brake"] and stop_condition(state):
            phase = "hold"
            hold_count = 1
        elif phase == "brake" and float(state["v"]) <= stop_speed:
            # If braking finished too early because of raster/geometric noise,
            # resume a low-speed approach instead of holding far from the sign.
            phase = "approach"
        elif phase == "hold":
            hold_count += 1
            if hold_count >= hold_steps_required:
                stop_completed = True
                completion_dense_step = int(step)
                phase = "release"
                release_started = True
                release_dense_step = int(step + 1) if step + 1 < dense_steps else None

        if (step + 1) % save_stride == 0:
            saved_states.append([state["x"], state["y"], state["yaw"], state["v"]])
            saved_controls.append([steer, acc])

    dense = np.asarray(dense_states, dtype=np.float32)
    controls = np.asarray(dense_controls, dtype=np.float32)
    saved = np.asarray(saved_states, dtype=np.float32)
    saved_ctrl = np.asarray(saved_controls, dtype=np.float32)
    dense_target = np.asarray(dense_targets, dtype=np.float32)
    saved_target = dense_target[save_stride - 1::save_stride][:n_wp].copy()
    if len(saved_target) < n_wp:
        saved_target = np.pad(saved_target, (0, n_wp - len(saved_target)), mode="edge")

    return {
        "waypoints": saved[:, :2].copy(),
        "yaws": saved[:, 2].copy(),
        "speeds": saved[:, 3].copy(),
        "controls": saved_ctrl.copy(),
        "dense_xy": dense[:, :2].copy(),
        "dense_yaw": dense[:, 2].copy(),
        "dense_speed": dense[:, 3].copy(),
        "dense_controls": controls.copy(),
        "target_speed": float(saved_target[-1]) if len(saved_target) else 0.0,
        "target_speed_profile": saved_target.astype(np.float32),
        "dense_target_speed_profile": dense_target.astype(np.float32),
        "stop_then_go_stop_distance_m": float(stop_distance),
        "stop_then_go_hold_steps_required": int(hold_steps_required),
        "stop_then_go_completed": bool(stop_completed),
        "stop_then_go_completion_dense_step": completion_dense_step,
        "stop_then_go_release_started": bool(release_started),
        "stop_then_go_release_dense_step": release_dense_step,
    }


def _critical_actor_distance(factor: Dict) -> float:
    actor = (factor or {}).get("critical_actor") or {}
    if not actor.get("exists", False):
        return float("inf")
    try:
        x = float(actor.get("x_m", actor.get("distance_m", float("inf"))))
        if x < 0.0:
            return float("inf")
        return x
    except Exception:
        return float("inf")


def _has_direct_front_factor(factor: Dict) -> bool:
    ftype = str((factor or {}).get("type", ""))
    actor = (factor or {}).get("critical_actor") or {}
    if actor.get("exists", False):
        rel = str(actor.get("relative_position", ""))
        return rel in ["front", "front_left", "front_right"] and _critical_actor_distance(factor) < 22.0
    return ftype in [
        "front_actor",
        "pedestrian_crossing_or_near_path",
        "front_static_obstacle",
        "front_left_static_obstacle",
        "front_right_static_obstacle",
        "limited_forward_space",
        "costmap_blocked_corridor",
    ]


def target_speed_for_intent(intent_name: str, measurement: Dict, cfg, factor: Dict = None, expert_future: Optional[np.ndarray] = None) -> float:
    cur = max(float(measurement.get("speed", 0.0)), 0.0)
    nominal = current_target_speed(measurement, cfg, expert_future=expert_future)
    beh = _cfg_get(cfg, "behaviors", {})
    min_speed = _cfg_float(beh, "min_rollout_speed_mps", 0.5)

    if intent_name == "route_follow":
        return nominal

    if intent_name == "cautious_follow":
        ratio = _cfg_float(beh, "cautious_speed_ratio", 0.90)
        floor_speed = _cfg_float(beh, "cautious_min_speed_mps", 7.0)
        soft_cap = _cfg_float(beh, "cautious_speed_mps", max(floor_speed, nominal * ratio))

        target = min(nominal, max(floor_speed, nominal * ratio, cur * ratio))
        target = min(target, soft_cap)

        if _has_direct_front_factor(factor or {}):
            d = _critical_actor_distance(factor or {})
            close_d = _cfg_float(beh, "cautious_close_distance_m", 9.0)
            near_d = _cfg_float(beh, "cautious_near_distance_m", 16.0)
            if d <= close_d:
                target = min(target, _cfg_float(beh, "cautious_close_speed_mps", 3.0))
            elif d <= near_d:
                target = min(target, _cfg_float(beh, "cautious_near_speed_mps", 5.5))

        return max(min_speed, target)

    if intent_name in ["left_nudge", "right_nudge"]:
        ratio = _cfg_float(beh, "nudge_speed_ratio", 0.90)
        floor_speed = _cfg_float(beh, "nudge_min_speed_mps", 7.0)
        cap = _cfg_float(beh, "nudge_speed_mps", 18.0)
        target = min(nominal, max(floor_speed, nominal * ratio, cur * ratio))
        return max(min_speed, min(target, cap))

    if intent_name == "creep":
        return float(cfg.behaviors.creep_speed_mps)
    if intent_name in ["yield_stop", "emergency_brake"]:
        return 0.0
    return nominal


def _response_speed_profiles(intent_name: str, measurement: Dict, cfg, factor: Dict, expert_future: Optional[np.ndarray]) -> List[Tuple[str, np.ndarray, float]]:

    nominal = nominal_speed_profile(measurement, cfg, expert_future=expert_future)
    expert = _future_speed_profile_from_waypoints(expert_future, cfg)
    rg = _cfg_get(cfg, "response_generation", {})

    if intent_name == "route_follow":
        return [("nominal", nominal, 0.0)]

    if intent_name == "cautious_follow":
        strengths = _cfg_list(rg, "longitudinal_response_strengths", [0.35, 0.65, 1.0]) # 3种响应强度 轻度减速、中度减速、完整减速
        fallback_ratios = _cfg_list(rg, "fallback_cautious_speed_ratios", [0.95, 0.85, 0.70])
        scalar_cap = target_speed_for_intent(intent_name, measurement, cfg, factor=factor, expert_future=expert_future)
        out = []
        for i, strength in enumerate(strengths):
            s = float(np.clip(strength, 0.0, 1.5))
            if expert is not None and len(expert) == len(nominal):
                # Only the slower-than-nominal portion of expert motion acts as
                # the response anchor.  Faster expert segments do not inflate a
                # cautious candidate.
                anchor = np.minimum(expert, nominal)
            else:
                ratio = fallback_ratios[min(i, len(fallback_ratios) - 1)] if fallback_ratios else max(0.3, 1.0 - 0.2 * s)
                anchor = nominal * float(ratio)

            # A close object defines the strongest response anchor, but weaker
            # variants interpolate toward it instead of all being hard-capped to
            # the same low speed.  This is essential for minimum-response
            # selection: 35%, 65%, and 100% responses must remain distinct.
            if _has_direct_front_factor(factor):
                anchor = np.minimum(anchor, float(scalar_cap))
            profile = nominal + s * (anchor - nominal)
            min_speed = _cfg_float(_cfg_get(cfg, "behaviors", {}), "min_rollout_speed_mps", 0.5)
            profile = np.clip(profile, min_speed, float(cfg.bicycle.max_speed_mps)).astype(np.float32)
            out.append(("longitudinal_%02d" % i, profile, s))
        return out

    if intent_name in ["left_nudge", "right_nudge"]:
        blend = _cfg_float(rg, "lateral_speed_response_strength", 0.35)
        if expert is not None and len(expert) == len(nominal):
            anchor = np.minimum(expert, nominal)
            profile = nominal + float(np.clip(blend, 0.0, 1.0)) * (anchor - nominal)
        else:
            profile = nominal.copy()
        cap = target_speed_for_intent(intent_name, measurement, cfg, factor=factor, expert_future=expert_future)
        profile = np.minimum(profile, cap).astype(np.float32)
        return [("adaptive_lateral", profile, float(blend))]

    if intent_name == "creep":
        value = target_speed_for_intent(intent_name, measurement, cfg, factor=factor, expert_future=expert_future)
        return [("creep", np.full_like(nominal, value), 1.0)]

    if intent_name in ["yield_stop", "emergency_brake"]:
        return [("stop", np.zeros_like(nominal), 1.0)]

    value = target_speed_for_intent(intent_name, measurement, cfg, factor=factor, expert_future=expert_future)
    return [("default", np.full_like(nominal, value), 1.0)]


def _route_y_near_actor(base_route: np.ndarray, actor: Dict) -> float:
    if base_route is None or len(base_route) == 0:
        return 0.0
    p = np.asarray([float(actor.get("x_m", 0.0)), float(actor.get("y_m", 0.0))], dtype=np.float32)
    d = np.linalg.norm(np.asarray(base_route, dtype=np.float32)[:, :2] - p[None, :], axis=1)
    return float(np.asarray(base_route, dtype=np.float32)[int(np.argmin(d)), 1])


def _adaptive_lateral_offset(intent_name: str, base_route: np.ndarray, factor: Dict, cfg) -> float:
    actor = (factor or {}).get("critical_actor") or {}
    beh = _cfg_get(cfg, "behaviors", {})
    rg = _cfg_get(cfg, "response_generation", {})

    default = abs(_cfg_float(beh, "left_nudge_offset_m" if intent_name == "left_nudge" else "right_nudge_offset_m", 1.0))
    if not actor.get("exists", False):
        return -default if intent_name == "left_nudge" else default

    route_y = _route_y_near_actor(base_route, actor)
    actor_y = float(actor.get("y_m", 0.0))
    actor_half_w = max(float(actor.get("half_width_m", 1.0)), 0.1)
    ego_half_w = float(cfg.vehicle.ego_half_width_m)
    margin = _cfg_float(rg, "lateral_safety_margin_m", 0.45)
    min_abs = _cfg_float(rg, "min_adaptive_nudge_offset_m", 0.45)
    max_abs = _cfg_float(rg, "max_adaptive_nudge_offset_m", 2.8)
    clearance = ego_half_w + actor_half_w + margin

    if intent_name == "left_nudge":
        target_y = actor_y - clearance
        offset = min(-min_abs, target_y - route_y)
    else:
        target_y = actor_y + clearance
        offset = max(min_abs, target_y - route_y)

    return float(np.clip(offset, -max_abs, max_abs))


def _adaptive_lateral_geometry(base_route: np.ndarray, factor: Dict, cfg) -> Tuple[float, float, float, float]:
    actor = (factor or {}).get("critical_actor") or {}
    beh = _cfg_get(cfg, "behaviors", {})
    rg = _cfg_get(cfg, "response_generation", {})

    if not actor.get("exists", False):
        return (
            float(cfg.behaviors.nudge_start_m),
            float(cfg.behaviors.nudge_transition_m),
            float(cfg.behaviors.nudge_return_start_m),
            float(cfg.behaviors.nudge_return_transition_m),
        )

    x = max(float(actor.get("x_m", 0.0)), 0.0)
    half_l = max(float(actor.get("half_length_m", 1.0)), 0.1)
    anticipation = _cfg_float(rg, "lateral_anticipation_m", 9.0)
    return_margin = _cfg_float(rg, "lateral_return_margin_m", 5.0)
    start = max(_cfg_float(rg, "min_nudge_start_m", 1.0), x - anticipation)
    transition = min(float(cfg.behaviors.nudge_transition_m), max(3.0, x - start))
    return_start = max(start + transition + 1.0, x + half_l + return_margin)
    return_transition = float(cfg.behaviors.nudge_return_transition_m)
    return float(start), float(transition), float(return_start), float(return_transition)


def _stop_distance_for_actor(factor: Dict, cfg, emergency: bool = False) -> float:
    if emergency:
        return float(cfg.behaviors.emergency_stop_distance_m)

    # Traffic-rule stop distances are derived from the actual red stop-line mask.
    # They represent the ego-center target that keeps the front edge before the line.
    rule_stop = (factor or {}).get("required_stop_distance_m", None)
    if rule_stop is not None:
        try:
            value = float(rule_stop)
            if np.isfinite(value):
                return max(value, 0.0)
        except Exception:
            pass

    actor = (factor or {}).get("critical_actor") or {}
    if not actor.get("exists", False) or float(actor.get("x_m", -1.0)) <= 0.0:
        return float(cfg.behaviors.default_stop_distance_m)

    rg = _cfg_get(cfg, "response_generation", {})
    actor_x = float(actor.get("x_m", cfg.behaviors.default_stop_distance_m))
    actor_half_l = max(float(actor.get("half_length_m", 1.0)), 0.1)
    ego_half_l = float(cfg.vehicle.ego_half_length_m)
    extra_margin = _cfg_float(rg, "longitudinal_safety_margin_m", float(cfg.behaviors.stop_margin_m))
    stop_d = actor_x - actor_half_l - ego_half_l - extra_margin
    return max(float(cfg.behaviors.min_stop_distance_m), float(stop_d))


def reference_routes_for_intent(intent_name: str, base_route: np.ndarray, factor: Dict, cfg) -> List[Tuple[str, np.ndarray, float, str]]:
    
    rg = _cfg_get(cfg, "response_generation", {})

    # 如果是横向微调行为，则需要生成多条横向偏移路线
    if intent_name in ["left_nudge", "right_nudge"]:
        # 需要的横向偏移（计算方式: 自车半宽+对象半宽+安全裕量）
        required = _adaptive_lateral_offset(intent_name, base_route, factor, cfg)
        # 生成3个横向强度的偏移路线，分别是0.8倍、1.0倍、1.2倍的横向偏移量
        scales = _cfg_list(rg, "lateral_offset_scales", [0.80, 1.00, 1.20])
        # 什么时候开始横移、多长距离完成横移、什么时候越过对象后开始回归、多长距离回到原路线
        start, transition, return_start, return_transition = _adaptive_lateral_geometry(base_route, factor, cfg)
        out = []
        for i, scale in enumerate(scales):
            offset = float(required) * max(float(scale), 0.1)
            ref = make_lateral_offset_route(
                base_route,
                offset_m=offset,
                start_m=start,
                transition_m=transition,
                return_start_m=return_start,
                return_transition_m=return_transition,
            )
            desc = "adaptive %s offset %.2f m around critical object" % ("left" if offset < 0 else "right", offset)
            out.append(("lateral_%02d" % i, ref.astype(np.float32), float(scale), desc))
        return out

    if intent_name in ["yield_stop", "emergency_brake"]:
        # 根据actor的纵向位置，计算出需要停车的距离，然后生成一条停车路线
        stop_d = _stop_distance_for_actor(factor, cfg, emergency=(intent_name == "emergency_brake"))
        ref = make_stop_route(base_route, stop_distance_m=stop_d)
        return [("stop", ref.astype(np.float32), 1.0, "stop route at %.1f m" % stop_d)]

    return [("base", base_route.copy().astype(np.float32), 0.0, "reference route")]


def _response_object_from_factor(factor: Dict) -> Dict:
    actor = (factor or {}).get("critical_actor") or {}
    if not actor.get("exists", False):
        return {"exists": False}
    out = {
        "exists": True,
        "id": actor.get("id", None),
        "class": actor.get("class", "unknown"),
        "relative_position": actor.get("relative_position", "unknown"),
        "x_m": float(actor.get("x_m", 0.0)),
        "y_m": float(actor.get("y_m", 0.0)),
    }
    return out

def _profile_to_horizon(values, n: int, fallback: np.ndarray) -> np.ndarray:
    """Return a finite waypoint-rate profile with exactly ``n`` samples."""
    arr = np.asarray(values if values is not None else [], dtype=np.float32).reshape(-1)
    arr = arr[np.isfinite(arr)]
    if len(arr) == 0:
        arr = np.asarray(fallback, dtype=np.float32).reshape(-1)
        arr = arr[np.isfinite(arr)]
    if len(arr) == 0:
        arr = np.zeros((n,), dtype=np.float32)
    if len(arr) == n:
        return arr.astype(np.float32)
    src = np.linspace(0.0, 1.0, len(arr), dtype=np.float32)
    dst = np.linspace(0.0, 1.0, n, dtype=np.float32)
    return np.interp(dst, src, arr).astype(np.float32)


def _route_to_count(route: np.ndarray, count: int, fallback: np.ndarray) -> np.ndarray:
    """Resample a route by normalized index so route blends keep one shape."""
    arr = np.asarray(route if route is not None else [], dtype=np.float32)
    if arr.ndim != 2 or len(arr) < 2 or arr.shape[1] < 2:
        arr = np.asarray(fallback, dtype=np.float32)
    arr = arr[:, :2]
    if len(arr) == count:
        return arr.astype(np.float32)
    src = np.linspace(0.0, 1.0, len(arr), dtype=np.float32)
    dst = np.linspace(0.0, 1.0, count, dtype=np.float32)
    x = np.interp(dst, src, arr[:, 0])
    y = np.interp(dst, src, arr[:, 1])
    return np.stack([x, y], axis=1).astype(np.float32)


def build_boundary_refined_candidate(
    selected_candidate: Dict,
    base_route: np.ndarray,
    reference_rollout: Dict,
    measurement: Dict,
    cfg,
    response_scale: float,
) -> Optional[Dict]:
    """Create a physically rolled-out response between zero and a safe candidate.

    ``response_scale=1`` reproduces the selected discrete response parameterization.
    ``response_scale=0`` removes the selected response geometry and moves its speed
    profile toward the current reference response.  Only response families with a
    meaningful continuous strength are supported; hard-rule stop/hold behaviors are
    intentionally excluded because their semantics are state-machine constraints,
    not tunable response magnitudes.
    """
    name = str(selected_candidate.get("intent_name", ""))
    if name not in ["cautious_follow", "left_nudge", "right_nudge"]:
        return None

    alpha = float(np.clip(response_scale, 0.0, 1.0))
    base = np.asarray(base_route, dtype=np.float32)
    if base.ndim != 2 or len(base) < 2 or base.shape[1] < 2:
        return None
    base = base[:, :2]

    upper_route = _route_to_count(selected_candidate.get("reference_route"), len(base), base)
    if name in ["left_nudge", "right_nudge"]:
        # Scale the actual selected offset geometry continuously back to the base route.
        refined_route = base + alpha * (upper_route - base)
    else:
        # Longitudinal refinement keeps the selected route geometry unchanged.
        refined_route = upper_route.copy()

    n = int(cfg.horizon.num_future_waypoints)
    nominal = nominal_speed_profile(measurement, cfg, expert_future=None)
    lower_profile = _profile_to_horizon(
        reference_rollout.get("target_speed_profile", reference_rollout.get("speeds", [])),
        n,
        nominal,
    )
    upper_profile = _profile_to_horizon(
        selected_candidate.get("target_speed_profile", selected_candidate.get("rollout", {}).get("target_speed_profile", [])),
        n,
        lower_profile,
    )
    refined_profile = lower_profile + alpha * (upper_profile - lower_profile)
    refined_profile = np.clip(refined_profile, 0.0, float(cfg.bicycle.max_speed_mps)).astype(np.float32)

    roll = rollout(refined_route.astype(np.float32), refined_profile, measurement, cfg)
    upper_level = float(selected_candidate.get("response_level", 0.0))
    parent_variant = str(selected_candidate.get("variant_id", "default"))
    return {
        "intent": dict(selected_candidate.get("intent", {})),
        "intent_name": name,
        "variant_id": "%s__boundary_%04d" % (parent_variant, int(round(alpha * 10000.0))),
        "response_level": float(upper_level * alpha),
        "reference_mode": "continuous boundary refinement of %s" % str(selected_candidate.get("reference_mode", "response")),
        "reference_route": refined_route.astype(np.float32),
        "target_speed": float(roll.get("target_speed", 0.0)),
        "target_speed_profile": refined_profile.astype(np.float32),
        "response_object": dict(selected_candidate.get("response_object", {"exists": False})),
        "boundary_parent_variant_id": parent_variant,
        "boundary_response_scale": float(alpha),
        "boundary_upper_response_level": float(upper_level),
        "rollout": roll,
    }

def build_candidates(base_route: np.ndarray, intents: List[Dict], factor: Dict, measurement: Dict, cfg, expert_future: Optional[np.ndarray] = None) -> List[Dict]:
    
    candidates = []
    response_object = _response_object_from_factor(factor)
    hold_active_rule = _active_rule_hold_required(factor, measurement, expert_future, cfg)

    for item in intents:
        name = item["intent_name"]

        # A stop sign and a nearer front actor are composed as a joint
        # longitudinal constraint.  The immediate response is to stop behind
        # the actor and hold there; this early stop does not falsely discharge
        # the later stop-sign obligation.  Once the actor no longer constrains
        # the route, a later frame can generate the ordinary stop-then-go rule
        # response near the sign.
        joint_constraint = (factor or {}).get("joint_longitudinal_constraint") or {}
        if (
            name == "yield_stop"
            and str((factor or {}).get("type", "")) == "stop_sign_control"
            and bool(joint_constraint.get("active", False))
        ):
            stop_d = _stop_distance_for_actor(factor, cfg, emergency=False)
            ref = make_stop_route(base_route, stop_distance_m=stop_d).astype(np.float32)
            speed_profile = np.zeros((int(cfg.horizon.num_future_waypoints),), dtype=np.float32)
            roll = rollout(ref, speed_profile, measurement, cfg)
            candidates.append({
                "intent": dict(item),
                "intent_name": name,
                "variant_id": "stop_sign__joint_constraint_hold",
                "response_level": 1.0,
                "reference_mode": "stop behind nearer actor while preserving the upcoming stop-sign obligation",
                "reference_route": ref,
                "target_speed": float(roll.get("target_speed", 0.0)),
                "target_speed_profile": speed_profile,
                "response_object": dict(response_object),
                "joint_longitudinal_constraint": dict(joint_constraint),
                "rollout": roll,
            })
            continue

        # Stop signs without a nearer actor require a complete stop followed by
        # release. Generate the whole stateful response on the original route
        # instead of reusing a permanent stop route.
        if name == "yield_stop" and str((factor or {}).get("type", "")) == "stop_sign_control":
            roll = _stop_sign_stop_then_go_rollout(
                base_route,
                factor,
                measurement,
                cfg,
                expert_future=expert_future,
            )
            candidates.append({
                "intent": dict(item),
                "intent_name": name,
                "variant_id": "stop_sign__stop_then_go",
                "response_level": 1.0,
                "reference_mode": "complete stop at stop sign, hold briefly, then proceed",
                "reference_route": np.asarray(base_route, dtype=np.float32).copy(),
                "target_speed": float(roll.get("target_speed", 0.0)),
                "target_speed_profile": np.asarray(roll.get("target_speed_profile", []), dtype=np.float32),
                "response_object": dict(response_object),
                "rollout": roll,
            })
            continue

        # If the ego has already completed the physical stopping motion under a
        # currently active red light, the correct label is an explicit hold.
        # Stop signs are handled above by the stop-then-go state machine.
        if name == "yield_stop" and hold_active_rule:
            ref = np.zeros_like(np.asarray(base_route, dtype=np.float32))
            if ref.ndim != 2 or ref.shape[1] < 2:
                ref = np.zeros((2, 2), dtype=np.float32)
            else:
                ref = ref[:, :2].astype(np.float32)
            roll = _stationary_hold_rollout(cfg)
            candidates.append({
                "intent": dict(item),
                "intent_name": name,
                "variant_id": "hold_current_stop__hold",
                "response_level": 1.0,
                "reference_mode": "hold current stopped pose while traffic rule remains active",
                "reference_route": ref,
                "target_speed": 0.0,
                "target_speed_profile": np.zeros((int(cfg.horizon.num_future_waypoints),), dtype=np.float32),
                "response_object": dict(response_object),
                "rollout": roll,
            })
            continue

        # 几何
        geometry_variants = reference_routes_for_intent(name, base_route, factor, cfg)
        # 速度
        speed_variants = _response_speed_profiles(name, measurement, cfg, factor, expert_future)

        for geom_id, ref, geom_level, ref_mode in geometry_variants:
            for speed_id, speed_profile, speed_level in speed_variants:
                # Avoid a combinatorial explosion: lateral intents use their one
                # lateral speed profile; longitudinal intents use base geometry.
                if name in ["left_nudge", "right_nudge"] and speed_id != "adaptive_lateral":
                    continue
                variant_id = "%s__%s" % (geom_id, speed_id)
                roll = rollout(ref, speed_profile, measurement, cfg)
                candidates.append({
                    "intent": dict(item),
                    "intent_name": name,
                    "variant_id": variant_id,
                    "response_level": float(max(geom_level, speed_level)),
                    "reference_mode": ref_mode,
                    "reference_route": ref,
                    "target_speed": float(roll.get("target_speed", 0.0)),
                    "target_speed_profile": np.asarray(speed_profile, dtype=np.float32),
                    "response_object": dict(response_object),
                    "rollout": roll,
                })
    return candidates


def build_nominal_reference_candidate(base_route: np.ndarray, measurement: Dict, cfg, expert_future: Optional[np.ndarray] = None) -> Dict:
    
    # 额定速度[10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0]
    profile = nominal_speed_profile(measurement, cfg, expert_future=expert_future)
    
    roll = rollout(base_route, profile, measurement, cfg)
    
    return {
        "intent": {
            "intent_id": 0,
            "intent_name": "route_follow",
            "intent_en": "follow the route",
            "active": True,
            "activation_reason": "nominal no-interference reference",
        },
        "intent_name": "route_follow",
        "variant_id": "nominal_reference",
        "response_level": 0.0,
        "reference_mode": "nominal no-interference route",
        "reference_route": base_route.copy().astype(np.float32),
        "target_speed": float(roll.get("target_speed", 0.0)),  # 目标速度
        "target_speed_profile": profile.astype(np.float32),
        "response_object": {"exists": False},
        "rollout": roll,
    }
