# -*- coding: utf-8 -*-

from .common import *
from .io_utils import load_json_gz
from .geometry_utils import ensure_route_starts_at_ego, global_point_to_current_ego_local

def get_meters_per_pixel(meta: Dict, default_pixels_per_meter: float) -> float:
    if "meters_per_pixel" in meta:
        return float(meta["meters_per_pixel"])

    if "pixels_per_meter" in meta:
        ppm = float(meta["pixels_per_meter"])
        if ppm <= 0:
            raise ValueError(f"Invalid pixels_per_meter in meta: {ppm}")
        return 1.0 / ppm

    if default_pixels_per_meter <= 0:
        raise ValueError(f"Invalid default_pixels_per_meter: {default_pixels_per_meter}")

    return 1.0 / float(default_pixels_per_meter)

def get_ego_center(meta: Dict, cost_shape: Tuple[int, int]) -> List[float]:
    h, w = cost_shape

    if "ego_center" in meta:
        center = meta["ego_center"]
        if isinstance(center, (list, tuple)) and len(center) == 2:
            return [float(center[0]), float(center[1])]

    # Fallback: image center.
    return [float(w // 2), float(h // 2)]

def route_from_measurement(measurement: Dict, route_key: str) -> np.ndarray:
    """
    Load local reference route from measurement.

    Expected shape:
        [[x, y], [x, y], ...]

    x is forward and y is right under the assumed SimLingo/TransFuser local route
    convention.
    """
    if route_key in measurement:
        route = measurement[route_key]
    elif "route" in measurement:
        LOGGER.warning(f"[Warn] route_key={route_key} not found. Fallback to 'route'.")
        route = measurement["route"]
    elif "route_original" in measurement:
        LOGGER.warning(f"[Warn] route_key={route_key} not found. Fallback to 'route_original'.")
        route = measurement["route_original"]
    else:
        raise KeyError(f"No route key found. Tried {route_key}, route, route_original.")

    route = np.asarray(route, dtype=np.float32)
    if route.ndim != 2 or route.shape[1] < 2:
        raise ValueError(f"Invalid route shape: {route.shape}")

    route = route[:, :2]
    route = ensure_route_starts_at_ego(route, prepend_threshold_m=0.5)

    return route

def get_current_ego_state(measurement: Dict) -> Dict:
    """
    Return current ego state in ego-local rollout frame.

    Rollout always starts from [x=0, y=0, yaw=0]. Speed comes from measurement.
    """
    speed = float(measurement.get("speed", 0.0))
    speed = max(speed, 0.0)
    return {"x": 0.0, "y": 0.0, "yaw": 0.0, "v": speed}

def load_future_ego_waypoints_from_measurements(
    route_dir: Path,
    frame_name: str,
    current_measurement: Dict,
    args,
) -> Optional[np.ndarray]:
    """
    Load actual future ego positions from future measurement files and convert
    them to current ego-local coordinates.

    This is only used as a saved reference field:
        expert_future_waypoints_from_measurements

    The risk_planned_waypoints are generated by bicycle rollout, not by reading
    future ego positions.
    """
    if "pos_global" not in current_measurement or "theta" not in current_measurement:
        return None

    try:
        frame_int = int(frame_name)
    except ValueError:
        return None

    ego_global = np.asarray(current_measurement["pos_global"][:2], dtype=np.float32)
    ego_yaw = float(current_measurement["theta"])

    future_points = []
    width = len(frame_name)

    for i in range(1, args.num_future_waypoints + 1):
        future_name = str(frame_int + i).zfill(width)
        future_path = route_dir / args.measurements_folder / f"{future_name}.json.gz"

        if not future_path.exists():
            break

        future_measurement = load_json_gz(future_path)
        if "pos_global" not in future_measurement:
            break

        p_global = np.asarray(future_measurement["pos_global"][:2], dtype=np.float32)
        p_local = global_point_to_current_ego_local(
            point_global=p_global,
            ego_global=ego_global,
            ego_yaw=ego_yaw,
        )
        future_points.append(p_local)

    if len(future_points) == 0:
        return None

    return np.asarray(future_points, dtype=np.float32)

def get_pose_global_xy_yaw(measurement: Dict) -> Optional[Tuple[np.ndarray, float]]:
    """
    Extract ego global XY and yaw from a measurement file.

    The current script already uses measurement['pos_global'] and
    measurement['theta'] for expert future waypoints. This helper keeps the
    same convention for temporal costmap warping.
    """
    if "pos_global" not in measurement or "theta" not in measurement:
        return None

    pos = np.asarray(measurement["pos_global"][:2], dtype=np.float32)
    yaw = float(measurement["theta"])
    if pos.shape[0] != 2 or not np.isfinite(pos).all() or not np.isfinite(yaw):
        return None
    return pos, yaw
